Description: >
  Beshoy Gendy / this script will create ec2 instance on aws 
  to practice configuring it with ansible

Parameters:
  EnvironmentName:
    Description: an environment name that will be prefixed to resources
    Type: String
  VpcId:
    Description: refer to default VPC ID
    Type: String


Resources:
  InstanceSec:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: allow traffic at port 3000 and ssh traffic
      VpcId: !Sub ${VpcId}
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: AnsibleSecGroup 

  AnsibleTestInstance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: opensasm
      ImageId: ami-0149b2da6ceec4bb0
      InstanceType: t3.micro
      SecurityGroupIds:
        - Ref: InstanceSec
      Tags:
        - Key: Name
          Value: test-instance
        - Key: Project
          Value: udacity
