version: 2.1

jobs:
  create-infrastructure:
    docker:
      - image: amazon/awc-cli
    steps:
      - checkout
      - run:
          name: "Create Cloudformation Stack"
          command: |
            aws cloudformation create-stack \
              --body-file ~/ansible-infra/test-instance.yml \
              --parameters ~/ansible-infra/infra-params.json \
              --region us-east-1


workflows:
  say-hello-workflow:
    jobs:
      - create-infrastructure
