version: 2.1

jobs:
  create-infrastructure:
    docker:
      - image: amazon/awc-cli
    steps:
      - checkout
      - run:
          name: "Create Cloudformation Stack"
          command: |
            aws cloudformation create-stack \
              --stack-name ansible-test
              --body-file test-instance.yml \
              --parameters infra-params.json \
              --region us-east-1


workflows:
  infrastructure-workflow:
    jobs:
      - create-infrastructure
